name: sup

on:
  push:
    branches:
      - main
    paths:
      - backend/**
jobs:
  what:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check fastapi
        working-directory: backend
        run: ls -A
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

