name: update db functions

on:
  push:
    branches:
      - main
    paths:
      - db/functions.sql
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update database functions
        working-directory: db
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          DB_PWD: ${{ secrets.DB_PWD }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} \
          "cd /home/ubuntu/bm/db
          psql -h localhost -d blackmetal -U postgres -tc \"select concat('drop function ',routine_name,';') from information_schema.routines where specific_catalog = 'blackmetal' and routine_schema = 'public';\" | psql -h localhost -d blackmetal -U postgres
          psql -h localhost -d blackmetal -U postgres -a -f functions.sql
          "
