name: update all

on:
  push:
    paths-ignore:
      - .github/workflows/**
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BACKEND_ENV: ${{ secrets.BACKEND_ENV }}
        run: |
          gh secret set BACKEND_ENV --repo Koji-Sunioj/bm-cfn --body "$BACKEND_ENV"
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} \
          "cd /home/ubuntu/bm
          git pull
          pip install -r /home/ubuntu/bm/backend/requirements.txt -q
          atlas schema apply -u 'postgres://postgres:${DB_PWD}@localhost:5432/blackmetal' --to file:///home/ubuntu/bm/db/atlas_schema.hcl --auto-approve
          echo $BACKEND_ENV | base64 -d > /home/ubuntu/bm/backend/.env
          sudo nginx -s reload
          lsof -t -i:8000 | xargs kill
          sudo -u ubuntu python3 -m gunicorn --worker-class uvicorn.workers.UvicornWorker --chdir /home/ubuntu/bm/backend/ --daemon main:app --error-logfile backend-error.log"
