name: sup

on:
  push:
    branches:
      - main
jobs:
  what:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: show conf
        run: cat api.conf
      - name: check flask
        working-directory: flask
        run: ls -A
      - name: echo something
        run: echo "hello wassup"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

